### PR TITLE
Reece/MoreMetadata

### PR DESCRIPTION
**Pull request by Reecepbcups**
<https://twitter.com/noahsaso/status/1629319268226732032?s=20>

Adds more metadata such as the token description, ticker, and exponent. Then a webapp can query it to properly

### Set Constraints
- Max Ticker Length: 6
- Max Exponent: 18
- Must be a factory/ denom AND you must be the admin of it to change
- no ticker can contain "juno" (any case) or a slash "/"
- Description limited to 255 characters
- Description blocks symbols `@#$^*<>;()`
- exponent must be positive

### Questions
- Should we allow the ticker to contain juno? just not start with it? (for LSD's using native tokens)

---

`BINARY tx tokenfactory modify-metadata $DENOM "ticker" "updated desc www.google.com" 18 $FLAGS`

Then a webapp can query the data with
`BINARY q bank denom-metadata --denom $DENOM --node http://localhost:26657`

```
metadata:
  base: factory/wasm1hj5fveer5cjtn4wd6wstzugjfdxzl0xpvsr89g/test
  denom_units:
  - aliases:
    - TICKER
    denom: factory/wasm1hj5fveer5cjtn4wd6wstzugjfdxzl0xpvsr89g/test
    exponent: 0
  - aliases:
    - factory/wasm1hj5fveer5cjtn4wd6wstzugjfdxzl0xpvsr89g/test
    denom: TICKER
    exponent: 18
  description: updated desc www.google.com
  display: factory/wasm1hj5fveer5cjtn4wd6wstzugjfdxzl0xpvsr89g/test
  name: factory/wasm1hj5fveer5cjtn4wd6wstzugjfdxzl0xpvsr89g/test
  symbol: TICKER
  ```

### CODE REVIEW

**Comment by Reecepbcups** [comment]
TODO: just deny adding a / in the symbol / denom alias.

**Comment by Reecepbcups** [comment]
TODO: 
- just deny adding a / in the symbol / denom alias from the CLI (for special demoms perfection)
- require the end of the factory/juno1.../subdenom to be somewhere in the pretty name & denom?

**Comment by faddat** [comment]
I think that allowing the ticker to contain Juno is totally okay.

**Comment by faddat** [comment]
Thanks so much dude

**Review by faddat — APPROVED** [review]

**Comment by faddat** [comment]
Hey one quick question before I smash the green button, I think that we would call these state breaking changes, correct?

**Comment by faddat** [comment]
Hey one quick question before I smash the green button, I think that we would call these state breaking changes, correct?

**Pull request merged**
